### ISSUE TITLE
Clarifications about the w2anims.json file format

### ISSUE THREAD

**Issue by strazto** [dingdio/witcher3-maya-animation#1]
I'm implementing this plugin in blender, since this plugin is the only reason I would otherwise need Maya in my workflow, and I'm finding that interchanging between Maya and blender isn't going particularly smoothly.

In particular, I'd like to get some reference for:

- "dataAddr" (+ fallback), & 
- some frame of reference for the array elements in:
  - "rotationFrames"
  - "positionFrames" 

I'd also like to understand the "_dt" keys - Does this represent a timestamp or something?

I also want to check whether, for an animation with 

```json
{
"numFrames" : global_num_frames
}
```

if, for a given bone in bones:
```json
{
   "BoneName" : "torso2",
   "position_numFrames" : ?
}
```

if the possible value for a "position/rotation/scale_numframes" element can take any value other than `global_num_frames`, or `1` . 

My assumption is that, given there's no keyframing/timing data encoded into each frame array element, for a given "position/rotation/scaleFrames" array, there must be either:
- An element for each frame of the animation, or
- One element, that sets a static frame for the animation.

Is this correct?

**Comment by strazto** [comment]
This spec likely belongs more to wkit than this plugin, I may reopen this there, but for now, I'm going to collect relevant wkit source links

https://github.com/Traderain/Wolven-kit/blob/master/WolvenKit.Render/Rig.cs
https://github.com/Traderain/Wolven-kit/blob/master/WolvenKit.Render/Animations.cs

https://github.com/Traderain/Wolven-kit/blob/master/WolvenKit.Render/Animation/ConvertAnimation.cs
https://github.com/Traderain/Wolven-kit/blob/master/WolvenKit.Render/Animation/ConvertRig.cs

https://github.com/Traderain/Wolven-kit/blob/master/WolvenKit.Render/Animation/ExportAnimation.cs

**EDIT**: Found your wkit PR https://github.com/Traderain/Wolven-kit/pull/160

**Comment by dingdio** [comment]
The json formats I've been using are a somewhat direct representations of data in witcher3 files with a few changes. The format is a work in progress by me. It will probably make a lot more sense if you look at a bunch of Witcher 3 files and understand how the game is reading them. From looking at the animation files in Witcher 3 I believe the REDkit sampled them from other animation formats as they came into their toolkit and baked them evenly.
So the "dt" is the deltatime of that particular baked bone. Which evenly spaces out all the keyframes. Each bone can have a different dt and there is also a dt for the entire animation, this global dt might be just a reference I forget.  So everything is baked evenly and dt determines the time between each frame.

- "dataAddr" (+ fallback), &

The dataAddr is a pointer to where the binary data of that bone position, orientation or scale starts inside the "data" block of an animation entry of an actual w2anims file. Don't really need this in the json it was just for figuring out how to edit existing animation. When you import the json with wolvenkit it will create new dataAddr. The numFrames and compression method will determine how long the data will read for.

Instead of using address pointers my format has completely uncompressed and plain numbers in those rotationFrames/positionFrames/scaleFrames arrays. That is the big difference from the real w2anims files. I might change how this works when I get back to working on this tool because this creates huge animation files. Good for research and manual editing but not for practice.

Each animation usually has fallback data that is used in case the animation doesn't load for some reason. This will be data with a single frame of animation.

Only the wolven-kit in this folder will work with the latest committed code:
https://mega.nz/folder/KMBHBQzZ#aLQCsUk0OZ50QSCJzWeuIw
The main wolven-kit hasn't been updated yet with the very latest. I plan to do another PR in the near future.

You should probably know that I originally started this project using Blender but abandoned it to work in Maya. I found the skeletons in Maya easier to work with and I think Blender would take a big performance hit once you start adding all the stuff I want to do with cutscenes, mimic animations and importing characters with all their items etc. A simple exporter of animation shouldn't be a problem in blender, apart from mimic animations for face/mouth movement. I have no idea how you would do that in Blender without a lot of programming. It's already pushing Maya to the limit loading all these face movements in animation layers.

**Comment by strazto** [comment]
thank you for the response - 
I eventually figured out my IO cycle troubles through the various tooling to get to Maya (It's a learning curve when you have to cycle through a few different programs with the same presets each time to convert things!) 

I think I like Maya for an end-point tool for exporting, at this point, as there is no systematic way to re-target animations in Blender (that I know of) like Maya's humanIK tool, & I've been very impressed with its capabilities in terms of providing consistent ways to map animations between rigs.

Given time, & finally figuring out a workflow (I've wound up committing a lot of presets to git because I found that reproducible import/export settings are very important here) that works has alleviated my concerns with using Maya.

Fortunately (for now) I'm not interested in Mimic animations, so won't have to open that can-of-worms
